/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as NoTenantProvidedRouteImport } from './routes/no-tenant-provided'
import { Route as IndexRouteImport } from './routes/index'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const NoTenantProvidedRoute = NoTenantProvidedRouteImport.update({
  id: '/no-tenant-provided',
  path: '/no-tenant-provided',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/no-tenant-provided': typeof NoTenantProvidedRoute
  '/not-found': typeof NotFoundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/no-tenant-provided': typeof NoTenantProvidedRoute
  '/not-found': typeof NotFoundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/no-tenant-provided': typeof NoTenantProvidedRoute
  '/not-found': typeof NotFoundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/no-tenant-provided' | '/not-found'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/no-tenant-provided' | '/not-found'
  id: '__root__' | '/' | '/no-tenant-provided' | '/not-found'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoTenantProvidedRoute: typeof NoTenantProvidedRoute
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-tenant-provided': {
      id: '/no-tenant-provided'
      path: '/no-tenant-provided'
      fullPath: '/no-tenant-provided'
      preLoaderRoute: typeof NoTenantProvidedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoTenantProvidedRoute: NoTenantProvidedRoute,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
